version: "3"
services:
  db_mutant:
    image: mysql:5.7.31
    environment:
      MYSQL_ROOT_PASSWORD: mutant
      MYSQL_DATABASE: mutantDB
    ports:
      - "3306"
  app:
    image: fabriciodorneles/desafio:desafio-nodejs_app
    depends_on:
      - db_mutant
    restart: on-failure
    ports:
      - 3333:3333
    command: sh -c "./node_modules/.bin/typeorm migration:run &&
           npm start"